services:
  r-core-mkdocs:
    image: squidfunk/mkdocs-material:9
    restart: unless-stopped
    ports:
      - "10004:8000"
    volumes:
      - ./config/mkdocs.yml:/docs/mkdocs.yml:ro
      - ./config/assets:/docs/docs/_app_assets:ro
      - ../../home/docs:/docs/docs