services:
  filebrowser:
    image: gtstef/filebrowser:latest
    container_name: r-core-filebrowser
    restart: unless-stopped

    ports:
      - "10002:80"

    environment:
      FILEBROWSER_CONFIG: "/home/filebrowser/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: "admin"

    volumes:
      - ../../:/folder
      - ./config/config.yaml:/home/filebrowser/config.yaml:ro
      - ../../var/lib/filebrowser:/home/filebrowser/database